"""Added slug columns

Revision ID: bf42b8de146b
Revises: 
Create Date: 2022-10-11 13:30:02.351877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf42b8de146b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcast',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=True),
    sa.Column('href', sa.String(), nullable=False),
    sa.Column('html_description', sa.String(), nullable=True),
    sa.Column('is_externally_hosted', sa.Boolean(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('total_episodes', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episode',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('podcast_id', sa.Integer(), nullable=True),
    sa.Column('audio_preview_url', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('explicit', sa.String(), nullable=True),
    sa.Column('external_urls', sa.String(), nullable=True),
    sa.Column('href', sa.String(), nullable=True),
    sa.Column('html_description', sa.String(), nullable=True),
    sa.Column('is_externally_hosted', sa.Boolean(), nullable=True),
    sa.Column('is_paywall_content', sa.Boolean(), nullable=True),
    sa.Column('is_playable', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug_name', sa.String(), nullable=False),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('release_date_precision', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('is_downloaded', sa.Boolean(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episode')
    op.drop_table('podcast')
    # ### end Alembic commands ###
